/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlguarderia;

import com.toedter.calendar.IDateEditor;
import com.toedter.calendar.JDateChooser;
import java.awt.Container;
import java.awt.EventQueue;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.PrintStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class Check extends javax.swing.JFrame {
    Cuidados cuida = new Cuidados();
    Conectar cc=new Conectar();
    Connection cn = cc.conexion();
    private ResultSet ver_gpos;
    private ResultSet ver_id_e,ver_id_s;
    private ResultSet chec_pad;
    private ResultSet chec_al;
    private ResultSet nin_den;
    private String rec_gpo_e,rec_gpo_s;
    private String rec_pad,rec_pad_s;
    private String rec_hij,rec_hij_s;
    private String rec_hor,rec_hor_s;
    protected String rec_fec,rec_fec_s;
    
    public Check() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/dd.jpg"));
        this.setIconImage(icon);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("REGISTRO DE ENTRADA Y SALIDA");
        ((JTextField)jfec.getDateEditor()).setEditable(false);
        ((JTextField)jfec_s.getDateEditor()).setEditable(false);
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/img/log.jpg")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        mostrar_gpo();
        ninios_den();
    }

    public String getRec_fec() {
        return rec_fec;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jgrup_e = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jid_nin_e = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jid_pad_e = new javax.swing.JTextField();
        jfec = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jreg_e = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jent = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jgrup_s = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jid_nin_s = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jsal = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jid_pad_s = new javax.swing.JTextField();
        jreg_s = new javax.swing.JButton();
        jfec_s = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jal_s = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jnin_den = new javax.swing.JTextArea();

        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Grupo");

        jgrup_e.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jgrup_e.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jgrup_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgrup_eActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("ID Niño:");

        jid_nin_e.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jid_nin_e.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jid_nin_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jid_nin_eActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("ID Padre o Tutor:");

        jid_pad_e.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jid_pad_eKeyTyped(evt);
            }
        });

        jfec.setDateFormatString("yyyy-MM-dd");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        jreg_e.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jreg_e.setText("Registrar entrada");
        jreg_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreg_eActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Hora de entrada:");

        jent.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00", "9:00", "10:00", "11:00" }));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setText("Alumno:");

        jal.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jid_pad_e)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jfec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jgrup_e, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jid_nin_e, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jreg_e)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jgrup_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jid_nin_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jid_pad_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jreg_e)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Check-in", jPanel2);

        jPanel3.setOpaque(false);

        jgrup_s.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jgrup_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jgrup_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgrup_sActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Grupo");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("ID Niño:");

        jid_nin_s.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jid_nin_s.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jid_nin_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jid_nin_sActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Hora de salida:");

        jsal.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12:00","1:00","2:00","3:00" }));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("ID Padre o Tutor:");

        jid_pad_s.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jid_pad_sKeyTyped(evt);
            }
        });

        jreg_s.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jreg_s.setText("Registrar salida");
        jreg_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreg_sActionPerformed(evt);
            }
        });

        jfec_s.setDateFormatString("yyyy-MM-dd");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Fecha:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("Alumno:");

        jal_s.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(298, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jreg_s))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(jfec_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jal_s, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jgrup_s, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jid_nin_s, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jid_pad_s)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jsal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap(129, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jal_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jfec_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jreg_s)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jgrup_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jid_nin_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(69, 69, 69)
                    .addComponent(jsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jid_pad_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Check-out", jPanel3);

        jPanel1.setOpaque(false);

        jnin_den.setEditable(false);
        jnin_den.setColumns(20);
        jnin_den.setRows(5);
        jScrollPane1.setViewportView(jnin_den);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Niños dentro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jreg_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreg_sActionPerformed
        rec_hij_s = String.valueOf(jid_nin_s.getSelectedItem());
        rec_pad_s = jid_pad_s.getText()+"-"+rec_hij_s;
        System.out.println(rec_pad_s);
        rec_hor_s = String.valueOf(jsal.getSelectedItem());
        rec_fec_s = ((JTextField)jfec_s.getDateEditor().getUiComponent()).getText();
        int i = 0;
        try
        {
            Statement consulta = cn.createStatement();
            chec_pad = consulta.executeQuery("SELECT * FROM checar");
            while(chec_pad.next()){
                if(chec_pad.getString(2).equals(rec_pad_s) && chec_pad.getString(5).equals(rec_fec_s)){
                    i++;
                }
            }
        }
        catch(SQLException sqlexception) { }
        if(i == 0){
            JOptionPane.showMessageDialog(null, "No hay coincidencia");
        }
        else{
            try
            {
                PreparedStatement pst = cn.prepareStatement("UPDATE checar SET hora_sal=?,chec_id_rec=? WHERE chec_id_ent='"+rec_pad_s+"'");
                pst.setString(1, rec_hor_s);
                pst.setString(2, rec_pad_s);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Niño fuera");
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "No coincide la fecha");
            }
        }
        ninios_den();
    }//GEN-LAST:event_jreg_sActionPerformed

    private void jgrup_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgrup_sActionPerformed
        mostrar_id();
    }//GEN-LAST:event_jgrup_sActionPerformed

    private void jgrup_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgrup_eActionPerformed
        mostrar_id();
    }//GEN-LAST:event_jgrup_eActionPerformed

    private void jreg_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreg_eActionPerformed
        rec_pad = jid_pad_e.getText();
        rec_hij = String.valueOf(jid_nin_e.getSelectedItem());
        rec_hor = String.valueOf(jent.getSelectedItem());
        rec_fec = ((JTextField)jfec.getDateEditor().getUiComponent()).getText();
        int i = 0;
        try
        {
            Statement consulta = cn.createStatement();
            chec_pad = consulta.executeQuery("SELECT * FROM hijos");
            while(chec_pad.next()){
                if(chec_pad.getString(1).equals(rec_hij) && chec_pad.getString(2).equals(rec_pad))
                i++;
            }
        }
        catch(SQLException sqlexception) { }
        if(i == 0)
            JOptionPane.showMessageDialog(null, "No hay coincidencia");
        else{
            try
            {
                PreparedStatement pst = cn.prepareStatement("INSERT INTO checar(chec_id_ni,chec_id_ent,hora_ent,hora_sal,fecha,chec_id_rec,grupo) VALUES (?,?,?,?,?,?,?)");
                pst.setString(1, "0");
                pst.setString(2, rec_pad+"-"+rec_hij);
                pst.setString(3, rec_hor);
                pst.setString(4, "0:00");
                pst.setString(5, rec_fec);
                pst.setString(6, "");
                pst.setString(7, rec_gpo_e);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Niño ingresado");
                this.dispose();
                cuida.setVisible(true);
                cuida.mostrar_nin_in(rec_fec,jal.getText(),rec_hij);
            }
            catch(Exception e)
            {
                System.out.println(e.getMessage());
            }
        }
        ninios_den();
    }//GEN-LAST:event_jreg_eActionPerformed

    private void jid_nin_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jid_nin_eActionPerformed
        try
        {
            Statement consulta = cn.createStatement();
            chec_al = consulta.executeQuery("SELECT * FROM ninios");
            while(chec_al.next()){
                if(chec_al.getString(1).equals(String.valueOf(jid_nin_e.getSelectedItem()))){
                    jal.setText(chec_al.getString(4)+" "+chec_al.getString(2)+" "+chec_al.getString(3));
                    break;
                }
                else{
                    jal.setText("");
                }
            }
        }
        catch(SQLException sqlexception) { }
    }//GEN-LAST:event_jid_nin_eActionPerformed

    private void jid_nin_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jid_nin_sActionPerformed
        try
        {
            Statement consulta = cn.createStatement();
            chec_al = consulta.executeQuery("SELECT * FROM ninios");
            while(chec_al.next()){
                if(chec_al.getString(1).equals(String.valueOf(jid_nin_s.getSelectedItem()))){
                    jal_s.setText(chec_al.getString(4)+" "+chec_al.getString(2)+" "+chec_al.getString(3));
                    break;
                }
                else{
                    jal_s.setText("");
                }
            }
        }
        catch(SQLException sqlexception) { }
    }//GEN-LAST:event_jid_nin_sActionPerformed

    private void jid_pad_eKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jid_pad_eKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'0' || get_car>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_jid_pad_eKeyTyped

    private void jid_pad_sKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jid_pad_sKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'0' || get_car>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_jid_pad_sKeyTyped

     public void mostrar_gpo()
    {
        jgrup_e.removeAllItems();
        jgrup_s.removeAllItems();
        int i = 0;
        try
        {
            Statement consulta = cn.createStatement();
            for(ver_gpos = consulta.executeQuery("SELECT * FROM grupos"); ver_gpos.next();)
            {
                jgrup_e.addItem(ver_gpos.getString(1));
                jgrup_s.addItem(ver_gpos.getString(1));
                i++;
            }

        }
        catch(SQLException sqlexception) { }
        if(i == 0)
        {
            jgrup_e.addItem("Necesita registrar grupos");
            jgrup_s.addItem("Necesita registrar grupos");
        }
    }

    public void mostrar_id()
    {
        jid_nin_e.removeAllItems();
        jid_nin_s.removeAllItems();
        rec_gpo_e = (String)jgrup_e.getSelectedItem();
        rec_gpo_s = (String)jgrup_s.getSelectedItem();
        int i = 0;
        int j = 0;
        try
        {
            Statement consulta = cn.createStatement();
            for(ver_id_e = consulta.executeQuery((new StringBuilder()).append("SELECT * FROM hijos WHERE id_grupo='").append(rec_gpo_e).append("'").toString()); ver_id_e.next();)
            {
                jid_nin_e.addItem(ver_id_e.getString(1));
                i++;
            }
            
            Statement consulta2 = cn.createStatement();
            for(ver_id_s = consulta2.executeQuery((new StringBuilder()).append("SELECT * FROM hijos WHERE id_grupo='").append(rec_gpo_s).append("'").toString()); ver_id_s.next();)
            {
                jid_nin_s.addItem(ver_id_s.getString(1));
                j++;
            }
            
        }
        catch(SQLException sqlexception) { }
        if(i == 0)
        {
            jid_nin_e.addItem((new StringBuilder()).append("No hay niños en el grupo:").append(rec_gpo_e).toString());
        }
        if(j == 0){
            jid_nin_s.addItem((new StringBuilder()).append("No hay niños en el grupo:").append(rec_gpo_s).toString());
        }
    }
    
    public void ninios_den(){
        String nin;
        jnin_den.setText("");
        
        try
        {
            Statement consulta = cn.createStatement();
            nin_den = consulta.executeQuery("SELECT * FROM checar");
            while(nin_den.next()){
                if(nin_den.getString(4).equals("00:00:00")){
                    nin=nin_den.getString(2);
                    jnin_den.append("ID:"+nin.substring(4,10)+"\t Grupo:"+
                            nin_den.getString(7)+"\tDia:"+
                            nin_den.getString(5)+"\n");
                }
            }
        }
        catch(SQLException sqlexception) { System.out.println(sqlexception.getMessage());}
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jal;
    private javax.swing.JTextField jal_s;
    private javax.swing.JComboBox<String> jent;
    private com.toedter.calendar.JDateChooser jfec;
    private com.toedter.calendar.JDateChooser jfec_s;
    private javax.swing.JComboBox<String> jgrup_e;
    private javax.swing.JComboBox<String> jgrup_s;
    private javax.swing.JComboBox<String> jid_nin_e;
    private javax.swing.JComboBox<String> jid_nin_s;
    private javax.swing.JTextField jid_pad_e;
    private javax.swing.JTextField jid_pad_s;
    private javax.swing.JTextArea jnin_den;
    private javax.swing.JButton jreg_e;
    private javax.swing.JButton jreg_s;
    private javax.swing.JComboBox<String> jsal;
    // End of variables declaration//GEN-END:variables
}
