/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlguarderia;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.*;
import org.jfree.data.category.DefaultCategoryDataset;

public class Graficas extends javax.swing.JFrame {

    JFreeChart grafica;
    DefaultCategoryDataset datos = new DefaultCategoryDataset();
    Conectar cc=new Conectar();
    Connection cn = cc.conexion();
    private ResultSet ver_gpo,ver_tot;
    private String gpo,fec,id_pad;
    private int meses[] = new int[12],total_nin; 
    
    public Graficas() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/dd.jpg"));
        this.setIconImage(icon);
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("OBSERVACIONES POR DIA");
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/img/graf.jpg")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jgrupo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setOpaque(false);

        jgrupo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jgrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        jgrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgrupoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Seleccione Grupo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void selecciona(){
        
        for(int i=0;i<12;i++){
            meses[i]=0;
        }
        
        gpo=(String)jgrupo.getSelectedItem();
        
        try
        {
            Statement consulta1 = cn.createStatement();
            ver_tot = consulta1.executeQuery("SELECT * FROM hijos WHERE id_grupo='"+gpo+"'");
            while(ver_tot.next()){
                if(ver_tot.getString(3).equals(gpo)){
                    total_nin++;
                }
            }
        }
        catch(SQLException sqlexception) { }
        
        try
        {
            Statement consulta = cn.createStatement();
            ver_gpo = consulta.executeQuery("SELECT * FROM checar WHERE grupo='"+gpo+"'");
            while(ver_gpo.next()){
                if(ver_gpo.getString(7).equals(gpo)){
                    fec=ver_gpo.getString(5);
                    llenar(fec.substring(5,7));
                }
            }
        }
        catch(SQLException sqlexception) { }
        
        datos.addValue(meses[0], "Ene", "Enero");
        datos.addValue(meses[1], "Feb", "Febrero");
        datos.addValue(meses[2], "Mar", "Marzo");
        datos.addValue(meses[3], "Abr", "Abril");
        datos.addValue(meses[4], "May", "Mayo");
        datos.addValue(meses[5], "Jun", "Junio");
        datos.addValue(meses[6], "Jul", "Julio");
        datos.addValue(meses[7], "Ago", "Agosto");
        datos.addValue(meses[8], "Sept", "Septiembre");
        datos.addValue(meses[9], "Oct", "Octubre");
        datos.addValue(meses[10], "Nov", "Noviembre");
        datos.addValue(meses[11], "Dic", "Diciembre");
        
        grafica = ChartFactory.createBarChart3D("Asistencia", "Mes", "Alumnos", datos,
        PlotOrientation.VERTICAL,true,true,false);
    }
   
    public void llenar(String mes){
        if(mes.equals("01")){
            meses[0]+=1;
        }
        else if(mes.equals("02")){
            meses[1]+=1;
        }
        else if(mes.equals("03")){
            meses[2]+=1;
        }
        else if(mes.equals("04")){
            meses[3]+=1;
        }
        else if(mes.equals("05")){
            meses[4]+=1;
        }
        else if(mes.equals("06")){
            meses[5]+=1;
        }
        else if(mes.equals("07")){
            meses[6]+=1;
        }
        else if(mes.equals("08")){
            meses[7]+=1;
        }
        else if(mes.equals("09")){
            meses[8]+=1;
        }
        else if(mes.equals("10")){
            meses[9]+=1;
        }
        else if(mes.equals("11")){
            meses[10]+=1;
        }
        else if(mes.equals("12")){
            meses[11]+=1;
        }
    }
    
    private void jgrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgrupoActionPerformed
        selecciona();
        ChartPanel Panel = new ChartPanel(grafica);
        JFrame Ventana = new JFrame("Grupo:"+gpo);
        Ventana.getContentPane().add(Panel);
        Ventana.pack();
        Ventana.setVisible(true);
        Ventana.setResizable(false);
        Ventana.setLocationRelativeTo(null);
        Ventana.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }//GEN-LAST:event_jgrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graficas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graficas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jgrupo;
    // End of variables declaration//GEN-END:variables
}
