/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlguarderia;

import com.toedter.calendar.IDateEditor;
import com.toedter.calendar.JDateChooser;
import java.awt.Container;
import java.awt.EventQueue;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.PrintStream;
import java.sql.*;
import java.util.Random;
import javax.swing.*;

public class Registro extends javax.swing.JFrame {
    Conectar cc=new Conectar();
    Connection cn = cc.conexion();
    private String id_pad = "";
    private String id_ni = "";
    private String rec_fec = "";
    private String rec_prof = "";
    private int encontrado = 0;
    private char def_gru;
    private final Date fecha_max = Date.valueOf("2015-10-01");
    private final Date fecha_min = Date.valueOf("2012-04-01");
    private ResultSet recibe_id;
    private ResultSet recibe_ape;
    private ResultSet verifica_pad;
    private ResultSet verifica_mae;
    
    public Registro() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/dd.jpg"));
        this.setIconImage(icon);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        ((JTextField)jfec.getDateEditor()).setEditable(false);
        this.setTitle("REGISTRO DEL NIÑO");
        jfec.setSelectableDateRange(fecha_min, fecha_max);
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/img/regs.jpg")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        japep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        japem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jselec_m = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jalergias = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jpadre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        japep_p = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jdire = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtelcont = new javax.swing.JTextField();
        jnomcont = new javax.swing.JTextField();
        jguarda = new javax.swing.JButton();
        jcoinci = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jfec = new com.toedter.calendar.JDateChooser();

        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomActionPerformed(evt);
            }
        });
        jnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jnomKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel3.setText("Apellido P:");

        japep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japepActionPerformed(evt);
            }
        });
        japep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                japepKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel4.setText("Apellido M:");

        japem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japemActionPerformed(evt);
            }
        });
        japem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                japemKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel1.setText("Fecha de nacimiento:");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setText("Maestro:");

        jselec_m.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jselec_m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel5.setText("Alergias");

        jalergias.setColumns(20);
        jalergias.setRows(5);
        jalergias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jalergiasKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jalergias);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel6.setText("Nombre del Padre o tutor:");

        jpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpadreActionPerformed(evt);
            }
        });
        jpadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpadreKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setText("Apellido P:");

        japep_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japep_pActionPerformed(evt);
            }
        });
        japep_p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                japep_pKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setText("Dirección:");

        jdire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdireActionPerformed(evt);
            }
        });
        jdire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jdireKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setText("Telefono:");

        jtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtelActionPerformed(evt);
            }
        });
        jtel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtelKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("PERSONA ADICIONAL");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel11.setText("Nombre:");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel12.setText("Telefono:");

        jtelcont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtelcontKeyTyped(evt);
            }
        });

        jnomcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnomcontActionPerformed(evt);
            }
        });
        jnomcont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jnomcontKeyTyped(evt);
            }
        });

        jguarda.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jguarda.setText("Registrar");
        jguarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jguardaActionPerformed(evt);
            }
        });

        jcoinci.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jcoinci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jcoinci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcoinciActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel14.setText("Coincidencias:");

        jfec.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(japem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jselec_m, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jfec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jnom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(japep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(170, 170, 170)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpadre)
                    .addComponent(japep_p)
                    .addComponent(jdire)
                    .addComponent(jtel)
                    .addComponent(jnomcont)
                    .addComponent(jtelcont, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcoinci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jguarda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jfec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(japep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(japem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jselec_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jpadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(japep_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcoinci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jdire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jnomcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jtelcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jguarda))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void japepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japepActionPerformed
        jcoinci.removeAllItems();
        int i = 0;
        try
        {
            Statement consulta = cn.createStatement();
            recibe_ape = consulta.executeQuery("SELECT * FROM padre_tutor");
            do
            {
                if(!recibe_ape.next())
                    break;
                if(recibe_ape.getString(3).equals(japep.getText()))
                {
                    jcoinci.addItem((new StringBuilder()).append("ID:").append(recibe_ape.getString(1)).append(" ").append(recibe_ape.getString(2)).append(" ").append(recibe_ape.getString(3)).toString());
                    i++;
                }
            } while(true);
        }
        catch(Exception exception) { }
        if(i == 0){
            jcoinci.addItem("No hay concidencias");
            jpadre.setText("");
            japep_p.setText("");
            jdire.setText("");
            jtel.setText("");
            jnomcont.setText("");
            jtelcont.setText("");
            jpadre.setEditable(true);
            japep_p.setEditable(true);
            jdire.setEditable(true);
            jtel.setEditable(true);
            jnomcont.setEditable(true);
            jtelcont.setEditable(true);
        }
        jcoinci.showPopup();
        japem.requestFocus();
    }//GEN-LAST:event_japepActionPerformed

    private void jguardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jguardaActionPerformed
        if(jnom.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Nombre vacio", "error", 0);
        else if(japep.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Apellido vacio", "error", 0);
        else if(japem.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Apellido vacio", "error", 0);
        else if(jalergias.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Alergias vacias", "error", 0);
        else if(jpadre.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Nombre del Padre o tutor vacio", "error", 0);
        else if(jdire.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Direccion vacia", "error", 0);
        else if(jtel.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Telefono vacio", "error", 0);
        else if(jnomcont.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Nombre de Persona adicional vacio", "error", 0);
        else if(jpadre.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Nombre de Padre vacio", "error", 0);
        else if(japep_p.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Apellido de Padre adicional vacio", "error", 0); 
        else if(jdire.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Direccion vacia", "error", 0); 
        else if(jtelcont.getText().isEmpty())
        JOptionPane.showMessageDialog(null, "Telefono de contacto", "error", 2);    
        else if(jfec.getDate() == null){
            JOptionPane.showMessageDialog(null, "Fecha vacia", "error", 0);
        }
        else if(jnom.getText().length()>10 ||
                japep.getText().length()>15 ||
                japem.getText().length()>15 ||
                jalergias.getText().length()>40 || 
                jnomcont.getText().length()>20 ||
                jpadre.getText().length()>20 ||
                japep_p.getText().length()>15 ||
                jdire.getText().length()>30 ||
                jtel.getText().length()>10 ||
                jtelcont.getText().length()>10 ){
            JOptionPane.showMessageDialog(null, "Error en la inserción de datos");
        }
        else{
            Random rnd = new Random();
            String abecedario = jnom.getText();
            if(jnom.getText().length() < 3)
            {
                JOptionPane.showMessageDialog(null, "El nombre debe ser mayor a 3 digitos", "error", 0);
            }
            else{
                label0:
                do
                {
                    encontrado = 0;
                    id_ni = id_pad = "";
                    try
                    {
                        int num = (int)(rnd.nextDouble() * 999D + 100D);
                        id_ni = (new StringBuilder()).append(id_ni).append(abecedario.charAt(0)).append(abecedario.charAt(1)).append(abecedario.charAt(2)).append(num).toString();
                        id_pad = (new StringBuilder()).append(id_pad).append(num).toString();
                        Statement consulta = cn.createStatement();
                        recibe_id = consulta.executeQuery("SELECT * FROM ninios");
                        do
                        {
                            if(!recibe_id.next())
                            break;
                            if(!recibe_id.getString(1).equals(id_ni))
                            continue;
                            encontrado = 1;
                            break;
                        } while(true);
                        recibe_id = consulta.executeQuery("SELECT * FROM padre_tutor");
                        do
                        if(!recibe_id.next())
                        continue label0;
                        while(!recibe_id.getString(1).equals(id_pad));
                        encontrado = 1;
                        continue;
                    }
                    catch(Exception exception1) { }
                }while(encontrado == 1);
                try
                {
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO ninios(id_ni,ni_apep,ni_apem,ni_nombre,ni_fec_nac,ni_aler) VALUES (?,?,?,?,?,?)");
                    pst.setString(1, id_ni);
                    pst.setString(2, japep.getText());
                    pst.setString(3, japem.getText());
                    pst.setString(4, jnom.getText());
                    pst.setString(5, ((JTextField)jfec.getDateEditor().getUiComponent()).getText());
                    pst.setString(6, jalergias.getText());
                    pst.execute();
                }
                catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
                try
                {
                    encontrado = 0;
                    Statement consulta = cn.createStatement();
                    verifica_pad = consulta.executeQuery("SELECT * FROM padre_tutor");
                    do
                    {
                        if(!verifica_pad.next())
                        break;
                        if(!verifica_pad.getString(2).equals(jpadre.getText()) || !verifica_pad.getString(3).equals(japep_p.getText()) || !verifica_pad.getString(5).equals(jtel.getText()))
                        continue;
                        id_pad = verifica_pad.getString(1);
                        encontrado = 1;
                        break;
                    } while(true);
                    if(encontrado == 0)
                    {
                        PreparedStatement pst = cn.prepareStatement("INSERT INTO padre_tutor(id_padre,nom_pad,ape_pat,dir_pad,tel_pad,nom_adic,tel_adic) VALUES (?,?,?,?,?,?,?)");
                        pst.setString(1, id_pad);
                        pst.setString(2, jpadre.getText());
                        pst.setString(3, japep_p.getText());
                        pst.setString(4, jdire.getText());
                        pst.setString(5, jtel.getText());
                        pst.setString(6, jnomcont.getText());
                        pst.setString(7, jtelcont.getText());
                        pst.execute();
                    }
                }
                catch(Exception e)
                {
                    System.out.println(e.getMessage());
                }
                try
                {
                    PreparedStatement pst = cn.prepareStatement("INSERT INTO hijos(id_hijo,id_padre,id_grupo,id_maes) VALUES (?,?,?,?)");
                    pst.setString(1, id_ni);
                    pst.setString(2, id_pad);
                    pst.setString(3, String.valueOf(def_gru));
                    pst.setString(4, rec_prof);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Niño registrado");
                }
                catch(Exception exception) { }
                id_ni = "";
                jnom.setText("");
                japep.setText("");
                japem.setText("");
                jalergias.setText(""); 
                jnomcont.setText("");
                jpadre.setText("");
                japep_p.setText("");
                jdire.setText("");
                jtel.setText("");
                jtelcont.setText("");
            }
        }
    }//GEN-LAST:event_jguardaActionPerformed

    private void jcoinciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcoinciActionPerformed
        String padre = (String)jcoinci.getSelectedItem();
        try
        {
            Statement consulta = cn.createStatement();
            recibe_ape = consulta.executeQuery("SELECT * FROM padre_tutor");
            do
            {
                if(!recibe_ape.next())
                break;
                if(recibe_ape.getString(1).equals(padre.substring(3, 6))){
                    jpadre.setText(recibe_ape.getString(2));
                    japep_p.setText(recibe_ape.getString(3));
                    jdire.setText(recibe_ape.getString(4));
                    jtel.setText(recibe_ape.getString(5));
                    jnomcont.setText(recibe_ape.getString(6));
                    jtelcont.setText(recibe_ape.getString(7));
                    jpadre.setEditable(false);
                    japep_p.setEditable(false);
                    jdire.setEditable(false);
                    jtel.setEditable(false);
                    jnomcont.setEditable(false);
                    jtelcont.setEditable(false);
                }
            } while(true);
        }
        catch(Exception exception) { }
    }//GEN-LAST:event_jcoinciActionPerformed

    private void japemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japemActionPerformed
        definir_grup();
        ver_maestros();
        selec_maes();
        jalergias.requestFocus();
    }//GEN-LAST:event_japemActionPerformed

    private void jnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomActionPerformed
        japep.requestFocus();
    }//GEN-LAST:event_jnomActionPerformed

    private void jpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpadreActionPerformed
        japep_p.requestFocus();
    }//GEN-LAST:event_jpadreActionPerformed

    private void japep_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japep_pActionPerformed
        jdire.requestFocus();
    }//GEN-LAST:event_japep_pActionPerformed

    private void jdireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdireActionPerformed
        jtel.requestFocus();
    }//GEN-LAST:event_jdireActionPerformed

    private void jnomcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnomcontActionPerformed
        jtelcont.requestFocus();
    }//GEN-LAST:event_jnomcontActionPerformed

    private void jtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtelActionPerformed
        jnomcont.requestFocus();
    }//GEN-LAST:event_jtelActionPerformed

    private void jnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnomKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_jnomKeyTyped

    private void japepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_japepKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_japepKeyTyped

    private void japemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_japemKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_japemKeyTyped

    private void jalergiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jalergiasKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_jalergiasKeyTyped

    private void jpadreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpadreKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_jpadreKeyTyped

    private void japep_pKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_japep_pKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_japep_pKeyTyped

    private void jdireKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdireKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_jdireKeyTyped

    private void jtelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtelKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'0' || get_car>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_jtelKeyTyped

    private void jnomcontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnomcontKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'a' || get_car>'z') && (get_car<'A' || get_car>'Z') && (get_car<' ' || get_car>' ')){
            evt.consume();
        }
    }//GEN-LAST:event_jnomcontKeyTyped

    private void jtelcontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtelcontKeyTyped
        char get_car=evt.getKeyChar();
        if((get_car<'0' || get_car>'9')){
            evt.consume();
        }
    }//GEN-LAST:event_jtelcontKeyTyped

    private void ver_maestros(){
        jselec_m.removeAllItems();
        int i = 0;
        try
        {
            Statement consulta = cn.createStatement();
            for(verifica_mae = consulta.executeQuery((new StringBuilder()).append("SELECT * FROM empleados WHERE grupo='").append(def_gru).append("'").toString()); verifica_mae.next();)
            {
                jselec_m.addItem((new StringBuilder()).append("ID:").append(verifica_mae.getString(1)).append(" ").append(verifica_mae.getString(2)).append(" ").append(verifica_mae.getString(3)).toString());
                i++;
            }

        }
        catch(SQLException sqlexception) { }
        if(i == 0)
            jselec_m.addItem("Necesita registrar maestros");
    }
    
     private void selec_maes(){
        String chec_prof = (String)jselec_m.getSelectedItem();
        try
        {
            Statement consulta = cn.createStatement();
            verifica_mae = consulta.executeQuery((new StringBuilder()).append("SELECT * FROM empleados WHERE grupo='").append(def_gru).append("'").toString());
            do
            {
                if(!verifica_mae.next())
                    break;
                if(verifica_mae.getString(1).equals(chec_prof.substring(3, 5)))
                    rec_prof = chec_prof.substring(3, 5);
            } while(true);
        }
        catch(SQLException sqlexception) { }
    }
     
     private void definir_grup(){
        rec_fec = ((JTextField)jfec.getDateEditor().getUiComponent()).getText();
        int mes = Integer.parseInt(rec_fec.substring(5, 7));
        int anio = Integer.parseInt(rec_fec.substring(0, 4));
        int dif_anio = 2017 - anio;
        int res = (4 - mes) + 12 * dif_anio;
        if(res >= 18 && res <= 24)
            def_gru = 'A';
        else if(res >= 25 && res <= 36)
            def_gru = 'B';
        else if(res >= 37 && res >= 48)
            def_gru = 'C';
        else if(res >= 49 && res <= 60)
            def_gru = 'D';
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jalergias;
    private javax.swing.JTextField japem;
    private javax.swing.JTextField japep;
    private javax.swing.JTextField japep_p;
    private javax.swing.JComboBox<String> jcoinci;
    private javax.swing.JTextField jdire;
    private com.toedter.calendar.JDateChooser jfec;
    private javax.swing.JButton jguarda;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jnomcont;
    private javax.swing.JTextField jpadre;
    private javax.swing.JComboBox<String> jselec_m;
    private javax.swing.JTextField jtel;
    private javax.swing.JTextField jtelcont;
    // End of variables declaration//GEN-END:variables
}
