/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlguarderia;

import com.itextpdf.text.BaseColor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class Reportes extends javax.swing.JFrame {
    Conectar cc=new Conectar();
    Connection cn = cc.conexion();
    private ResultSet ver_as,ver_id,ver_fec,ver_gpo;
    private String al,gpo,id_nin;
    

    
    public Reportes() {
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/dd.jpg"));
        this.setIconImage(icon);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("REPORTES");
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/img/rep.jpg")); 
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrep_as = new javax.swing.JButton();
        jrep_al = new javax.swing.JButton();

        jPanel1.setOpaque(false);

        jrep_as.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jrep_as.setText("Asistencia de niños");
        jrep_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrep_asActionPerformed(evt);
            }
        });

        jrep_al.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jrep_al.setText("Reporte de niños");
        jrep_al.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrep_alActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrep_al, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrep_as, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrep_al, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrep_as, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrep_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrep_asActionPerformed
        Document document = new Document();
        
        try
        {
            PdfWriter.getInstance(document, new FileOutputStream("ASISTENCIA.pdf"));
            document.open();
            
            // Este codigo genera una tabla de 3 columnas
            PdfPTable table = new PdfPTable(4);
            
            table.addCell("ID NIÑO");
            table.addCell("DIA");
            table.addCell("GRUPO");
            table.addCell("ASISTENCIA");
            
            Statement consulta = cn.createStatement();
            Statement consulta2 = cn.createStatement();
            ver_gpo = consulta.executeQuery("SELECT * FROM checar");
            while(ver_gpo.next()){
                gpo=ver_gpo.getString(7);
                ver_fec = consulta2.executeQuery("SELECT * FROM hijos WHERE id_grupo='"+gpo+"'");
                while(ver_fec.next()){
                    id_nin=ver_gpo.getString(2);
                    if((gpo.equals(ver_fec.getString(3))) && (ver_gpo.getString(2).equals(ver_fec.getString(2)+"-"+id_nin.substring(4, 10))) && (id_nin.substring(4, 10).equals(ver_fec.getString(1)))){
                        table.addCell(ver_fec.getString(1));
                        table.addCell(ver_gpo.getString(5));
                        table.addCell(gpo);
                        table.addCell("*");
                    }
                }
            }
            PdfPCell celdaFinal = new PdfPCell();
            
            // Indicamos cuantas columnas ocupa la celda
            celdaFinal.setColspan(4);
            table.addCell(celdaFinal);
             
            // Agregamos la tabla al documento            
            document.add(table);
             
            document.close();
            
        }
        catch(Exception e)
        {
            System.err.println("Ocurrio un error al crear el archivo");
            System.exit(0);
        }
    }//GEN-LAST:event_jrep_asActionPerformed

    private void jrep_alActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrep_alActionPerformed
        Document document = new Document();
        
        try
        {
            PdfWriter.getInstance(document, new FileOutputStream("NIÑOS.pdf"));
            document.open();
            
            // Este codigo genera una tabla de 3 columnas
            PdfPTable table = new PdfPTable(7);
            
            table.addCell("ID");
            table.addCell("NOMBRE");
            table.addCell("APELLIDO P");
            table.addCell("APELLIDO M");
            table.addCell("FEC. NAC.");
            table.addCell("ALERGIAS");
            table.addCell("CUIDADOS");
            
            Statement consulta = cn.createStatement();
            Statement consulta2 = cn.createStatement();
            ver_as = consulta.executeQuery("SELECT * FROM ninios");
            while(ver_as.next()){
                al=ver_as.getString(1);
                ver_id = consulta2.executeQuery("SELECT * FROM cuidados WHERE cui_id_ni='"+al+"'");
                while(ver_id.next()){
                    if(al.equals(ver_id.getString(1))){
                        table.addCell(ver_as.getString(1));
                        table.addCell(ver_as.getString(4));
                        table.addCell(ver_as.getString(2));
                        table.addCell(ver_as.getString(3));
                        table.addCell(ver_as.getString(5));
                        table.addCell(ver_as.getString(6));
                        table.addCell(ver_id.getString(2));
                    }
                }
            }
            PdfPCell celdaFinal = new PdfPCell();
            
            // Indicamos cuantas columnas ocupa la celda
            celdaFinal.setColspan(7);
            table.addCell(celdaFinal);
             
            // Agregamos la tabla al documento            
            document.add(table);
             
            document.close();
            
        }
        catch(Exception e)
        {
            System.err.println("Ocurrio un error al crear el archivo");
            System.exit(0);
        }
    }//GEN-LAST:event_jrep_alActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jrep_al;
    private javax.swing.JButton jrep_as;
    // End of variables declaration//GEN-END:variables
}
